-- AlterTable
ALTER TABLE "public"."Agreement" ALTER COLUMN "status" SET DEFAULT 'PENDING',
ALTER COLUMN "digitalSignature" DROP NOT NULL,
ALTER COLUMN "pdfFilePath" DROP NOT NULL;

-- AlterTable
ALTER TABLE "public"."Bank" ADD COLUMN     "createdById" INTEGER NOT NULL DEFAULT 1,
ALTER COLUMN "name" SET DATA TYPE TEXT,
ALTER COLUMN "contactEmail" SET DATA TYPE TEXT,
ALTER COLUMN "phone" SET DATA TYPE TEXT,
ALTER COLUMN "city" SET DATA TYPE TEXT,
ALTER COLUMN "state" SET DATA TYPE TEXT,
ALTER COLUMN "country" SET DATA TYPE TEXT,
ALTER COLUMN "postalCode" SET DATA TYPE TEXT,
ALTER COLUMN "ceoName" SET DATA TYPE TEXT,
ALTER COLUMN "ceoEmail" SET DATA TYPE TEXT,
ALTER COLUMN "ctoName" SET DATA TYPE TEXT,
ALTER COLUMN "ctoEmail" SET DATA TYPE TEXT,
ALTER COLUMN "swiftCode" SET DATA TYPE TEXT;

-- AddForeignKey
ALTER TABLE "public"."Bank" ADD CONSTRAINT "Bank_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "public"."User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
